apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: main
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - cleanup
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: nose
      taskRef:
        name: nose
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: args
          value: "-v"
